language: scala
scala:
  - 2.11.12
  - 2.12.4
jdk:
  - oraclejdk8
sudo: false
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- git diff --exit-code
addons:
  apt:
    packages:
      - oracle-java8-installer
